"""从 result/ 的 eval_results.csv / training_cost.csv 生成论文表格的 LaTeX 片段。

右键 Run 即可。产出写到 paper_assets/generated/，与修订稿（第二轮返修）
5.6.3 / 5.7 / 5.8 各表的 tabular 主体逐字对应——把生成的片段与
manuscript.tex 中对应表格 diff 一致，就是"数字可追溯"的验收标准。

统计口径（与论文 5.7 节协议声明一一对应）:
* 运营配置（tab_ratio / tab_capacity / tab_picktime；tab_capacity 自 round-7
  起为 C=1..5 的合并表；tab_layout 的数字自 round-5 起以正文行内形式出现在
  5.7.4，不再单列成表）
  —— SAPPO 取各配置独立训练中的最优（最小）平均流程时间；
     规则是确定性的，单次评测即可。全文口径 = 最优值，不报标准差。
* 消融合并表（tab_ablation = 原 tab_gamma + tab_state 两块合一，
  round-5 起论文只保留这一张消融表）
  —— 报 3 次独立训练的 mean ± std（ddof=1）：论证本身依赖
     run-to-run 方差与配对检验，删掉标准差论证就塌了。
* 训练成本表（tab_training_cost）—— 各配置 wall clock / 吞吐取均值。

缺哪个 run 目录就跳过对应表格并提示先跑哪个脚本，不会报错中断。
"""
from __future__ import annotations

import csv
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULT = os.path.join(ROOT, "result")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")

RULES = ("MQ-ND", "MQ-MinRQ", "MQ-MI", "MI-MinRQ", "MI-MI")
STREAMS = ("lam20", "lam40", "lam60")


# ---------------------------------------------------------------- 基础读取
def read_eval(run_name):
    """读一个 run 的 eval_results.csv -> {(instance_id, method): mean_flow_time}"""
    path = os.path.join(RESULT, run_name, "eval_results.csv")
    if not os.path.exists(path):
        return None
    out = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            out[(row["instance_id"], row["method"])] = float(row["mean_flow_time"])
    return out


def runs_of(prefix):
    """result/ 下形如 <prefix>_run<i> 的目录名列表（按 i 排序）。"""
    if not os.path.isdir(RESULT):
        return []
    names = [d for d in os.listdir(RESULT)
             if d.startswith(prefix + "_run") and
             os.path.isdir(os.path.join(RESULT, d))]
    return sorted(names)


def sappo_best(prefix, stream):
    """SAPPO 在 <prefix>_run* 各次独立训练中的最优（最小）F。"""
    vals = []
    for name in runs_of(prefix):
        data = read_eval(name)
        if data and (stream, "SAPPO") in data:
            vals.append(data[(stream, "SAPPO")])
    return min(vals) if vals else None


def sappo_runs(prefix, stream):
    """SAPPO 在 <prefix>_run* 各次训练的 F 列表（供 mean ± std 用）。"""
    vals = []
    for name in runs_of(prefix):
        data = read_eval(name)
        if data and (stream, "SAPPO") in data:
            vals.append(data[(stream, "SAPPO")])
    return vals


def rules_at(prefix_or_dir, stream):
    """五条规则在某配置下的 F（确定性；取第一个可用 run）。"""
    candidates = runs_of(prefix_or_dir) or [prefix_or_dir]
    for name in candidates:
        data = read_eval(name)
        if data:
            picked = {m: data[(stream, m)] for m in RULES if (stream, m) in data}
            if picked:
                return picked
    return {}


# ---------------------------------------------------------------- 格式化
def f1(x):
    return f"{x:.1f}"


def mean_std(vals):
    m = sum(vals) / len(vals)
    if len(vals) < 2:
        return f1(m)
    var = sum((v - m) ** 2 for v in vals) / (len(vals) - 1)
    return f"{m:.1f} $\\pm$ {math.sqrt(var):.1f}"


def gap_pct(rule, sappo):
    return f"{(rule - sappo) / rule * 100:.1f}\\%"


def write_fragment(filename, sources, header, rows, extra_comment=""):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, filename)
    ncols = header.count("&") + 1
    with open(path, "w") as f:
        f.write("% Generated by paper_assets/make_tables.py -- do not edit by hand.\n")
        f.write(f"% Sources: {', '.join(sources)}\n")
        if extra_comment:
            f.write(extra_comment.rstrip() + "\n")
        f.write("\\begin{tabular}{l" + "c" * (ncols - 1) + "}\n\\toprule\n")
        f.write(header + " \\\\\n\\midrule\n")
        for row in rows:
            f.write(row + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    print(f"  写出 {os.path.relpath(path, ROOT)}")
    return path


def skip(table, needed):
    print(f"  [跳过] {table}: 缺少 {needed} —— 先运行对应实验脚本")


# ---------------------------------------------------------------- 各表
def tab_ratio():
    configs = [
        ("1:1", 1, 1, "e1_k1r1"),
        ("3:1", 3, 1, "e1_k3r1"),
        ("4:2", 4, 2, "e1_k4r2"),
        ("3:6", 3, 6, "e0"),
        ("8:16", 8, 16, "e2_k8r16"),
        ("10:20", 10, 20, "e2_k10r20"),
    ]
    rows, sources = [], []
    for label, k, r, prefix in configs:
        sappo = sappo_best(prefix, "lam40")
        rules = rules_at(prefix, "lam40")
        if sappo is None or not rules:
            skip("tab_ratio", f"result/{prefix}_run*")
            return
        best_rule = min(rules, key=rules.get)
        rows.append(f"{label} & {k} & {r} & {f1(sappo)} & {best_rule} & "
                    f"{f1(rules[best_rule])} & {gap_pct(rules[best_rule], sappo)}")
        sources += runs_of(prefix)
    write_fragment("tab_ratio.tex", sorted(set(sources)),
                   "Ratio $K{:}R$ & $K$ & $R$ & SAPPO $\\bar{F}$ & Best rule & "
                   "Rule $\\bar{F}$ & Gap", rows)


def tab_capacity():
    """5.7.2 容量表（论文 Table 18）。

    round-7 起把原 tab_capacity（SAPPO + 规则，C=1..3）与
    tab_capacity_rules_sweep（规则，C=1..5）合并为一张：两者在 C=1,2,3 上的
    规则值本来就逐字节相同（规则确定性），分成两表纯属重复。SAPPO 只在
    C<=3 逐容量重训，C=4,5 填 "--"。
    """
    sappo_src = {1: "e0", 2: "e7_c2", 3: "e7_c3"}
    caps = [c for c in (1, 2, 3, 4, 5) if read_eval(f"rules_c{c}") is not None]
    if len(caps) < 4:
        skip("tab_capacity",
             "result/rules_c1..c5（experiment/run_e10_rules_capacity.py）")
        return
    per_c = {c: rules_at(f"rules_c{c}", "lam40") for c in caps}
    sappo = {}
    for c, prefix in sappo_src.items():
        v = sappo_best(prefix, "lam40")
        if v is None:
            skip("tab_capacity", f"result/{prefix}_run*")
            return
        sappo[c] = v
    rows = ["SAPPO & " + " & ".join(f1(sappo[c]) if c in sappo else "--"
                                    for c in caps)]
    for m in RULES:
        rows.append(m + " & " + " & ".join(f1(per_c[c][m]) for c in caps))
    rows.append("\\midrule\nBest rule & "
                + " & ".join(f1(min(per_c[c].values())) for c in caps))
    sources = sorted(set(sum((runs_of(p) for p in sappo_src.values()), [])
                         + [f"rules_c{c}" for c in caps]))
    write_fragment("tab_capacity.tex", sources,
                   "Method & " + " & ".join(f"$C={c}$" for c in caps), rows)


def tab_picktime():
    cols = [("$\\tau_{\\mathrm{pick}}=10$\\,s", "e0"),
            ("$\\tau_{\\mathrm{pick}}=15$\\,s", "e6_tau15"),
            ("$\\tau_{\\mathrm{pick}}=20$\\,s", "e6_tau20")]
    per_col = {}
    for label, prefix in cols:
        sappo = sappo_best(prefix, "lam40")
        rules = rules_at(prefix, "lam40")
        if sappo is None or not rules:
            skip("tab_picktime", f"result/{prefix}_run*")
            return
        per_col[label] = dict(rules, SAPPO=sappo)
    rows = [m + " & " + " & ".join(f1(per_col[label][m]) for label, _ in cols)
            for m in ("SAPPO",) + RULES]
    write_fragment("tab_picktime.tex",
                   sorted(set(sum((runs_of(p) for _, p in cols), []))),
                   "Method & " + " & ".join(label for label, _ in cols), rows)


def tab_layout():
    """E8 布局变体。round-5 起论文 5.7.4 不再单列此表，两组数字
    （1557.1→1079.2 / 1816.3→1089.7，MI-MI）以行内形式写进正文；
    本片段保留作为行内数字的数据溯源。"""
    base_sappo = sappo_best("e0", "lam40")
    base_rules = rules_at("e0", "lam40")
    mid_sappo = sappo_best("e8_mid", "lam40")
    mid_rules = rules_at("e8_mid", "lam40")
    if None in (base_sappo, mid_sappo) or not base_rules or not mid_rules:
        skip("tab_layout", "result/e0_run* 与 result/e8_mid_run*")
        return
    rows = []
    for label, sappo, rules in [
            ("Bottom + top cross-aisles (Eq. 2)", base_sappo, base_rules),
            ("+ middle cross-aisle", mid_sappo, mid_rules)]:
        best_rule = min(rules, key=rules.get)
        rows.append(f"{label} & {f1(sappo)} & {best_rule} & {f1(rules[best_rule])}")
    write_fragment("tab_layout.tex",
                   sorted(set(runs_of("e0") + runs_of("e8_mid"))),
                   "Layout & SAPPO $\\bar{F}$ & Best rule & Rule $\\bar{F}$", rows)


def tab_ablation():
    """5.8 合并消融表（tab:ablation）：上块折扣因子 γ、下块观测 s_t vs s_t^+。

    round-5 起论文把原 tab_gamma / tab_state 两张小表合并成这一张，
    行标签与论文逐字一致（$\\gamma = 0.95$ … / $s_t$ (4 channels) …）。
    """
    rows, sources = [], []
    rows.append("\\multicolumn{5}{l}{\\emph{Discount factor}}")
    for g in ("0.95", "0.99", "1.00"):
        prefix = f"e4_gamma{g}"
        cells, means = [], []
        for stream in STREAMS:
            vals = sappo_runs(prefix, stream)
            if not vals:
                skip("tab_ablation", f"result/{prefix}_run*")
                return
            cells.append(mean_std(vals))
            means.append(sum(vals) / len(vals))
        rows.append(f"$\\gamma = {g}$ & " + " & ".join(cells)
                    + f" & {f1(sum(means) / len(means))}")
        sources += runs_of(prefix)
    variants = [("$s_t$ (4 channels)", "e0"),
                ("$s_t^{+}$ (6 channels)", "e5_plus")]
    paired = {}
    obs_rows = []
    for label, prefix in variants:
        cells, means = [], []
        for stream in STREAMS:
            vals = sappo_runs(prefix, stream)
            if len(vals) < 2:
                skip("tab_ablation", f"result/{prefix}_run*（>= 2 次独立训练）")
                return
            cells.append(mean_std(vals))
            means.append(sum(vals) / len(vals))
            paired[(prefix, stream)] = vals
        obs_rows.append(f"{label} & " + " & ".join(cells)
                        + f" & {f1(sum(means) / len(means))}")
        sources += runs_of(prefix)
    rows.append("\\midrule\n\\multicolumn{5}{l}{\\emph{Observation}}")
    rows += obs_rows
    try:
        from scipy import stats as sps
        base, plus = [], []
        for stream in STREAMS:
            base += paired[("e0", stream)]
            plus += paired[("e5_plus", stream)]
        t, p = sps.ttest_rel(base, plus)
        comment = (f"% paired t-test (observation ablation) over {len(base)} "
                   f"(stream, run) pairs: t = {t:.3f}, p = {p:.4f}")
    except ImportError:
        comment = "% scipy 未安装，配对 t 检验略；pip install scipy 后重跑"
    write_fragment("tab_ablation.tex", sorted(set(sources)),
                   "Setting & $1/\\lambda=20$ & $1/\\lambda=40$ & "
                   "$1/\\lambda=60$ & Overall", rows, extra_comment=comment)


def tab_state_capacity():
    """E9: 容量 x 状态通道。round-5 起论文 5.8.2 不再单列此表，四个数字
    （1879.5→1743.4±52.5 / 1912.0→1839.4±49.0）以行内形式写进正文；
    本片段保留作为行内数字的数据溯源。"""
    combos = [("$C=2$", "e7_c2", "e9_c2_plus"), ("$C=3$", "e7_c3", "e9_c3_plus")]
    if not any(runs_of(p) for _, _, p in combos):
        skip("tab_state_capacity",
             "result/e9_c*_plus_run*（experiment/run_e9_capacity_state.py）")
        return
    rows, sources = [], []
    for label, base_prefix, plus_prefix in combos:
        base_vals = sappo_runs(base_prefix, "lam40")
        plus_vals = sappo_runs(plus_prefix, "lam40")
        if not base_vals or not plus_vals:
            skip("tab_state_capacity", f"result/{plus_prefix}_run*")
            return
        rows.append(f"{label} & {mean_std(base_vals)} & {mean_std(plus_vals)}")
        sources += runs_of(base_prefix) + runs_of(plus_prefix)
    write_fragment(
        "tab_state_capacity.tex", sorted(set(sources)),
        "Capacity & Base (4 channels) & + agent channels (6)", rows,
        extra_comment="% 注意: e7(base) 为 2000 轮、e9(plus) 默认 3000 轮；预算严格对齐\n"
                      "% 的对照请在 run_e9_capacity_state.py 打开 BUDGET_MATCHED_BASE。")


def tab_training_cost():
    configs = [(1, 1, "e1_k1r1"), (3, 1, "e1_k3r1"), (4, 2, "e1_k4r2"),
               (3, 6, "e0"), (8, 16, "e2_k8r16"), (10, 20, "e2_k10r20")]
    rows, sources = [], []
    for k, r, prefix in configs:
        recs = []
        for name in runs_of(prefix):
            path = os.path.join(RESULT, name, "training_cost.csv")
            if os.path.exists(path):
                with open(path, newline="") as f:
                    recs += list(csv.DictReader(f))
        if not recs:
            skip("tab_training_cost", f"result/{prefix}_run*/training_cost.csv")
            return
        n_actions = int(recs[0]["n_actions"])
        params = int(recs[0]["n_parameters"]) / 1e6
        episodes = int(recs[0]["n_episodes"])
        wall_h = sum(float(x["wall_clock_s"]) for x in recs) / len(recs) / 3600
        dps = sum(float(x["decisions_per_second"]) for x in recs) / len(recs)
        rows.append(f"{k} & {r} & {n_actions} & {params:.1f} & {episodes} & "
                    f"{wall_h:.1f} & {dps:.0f}")
        sources += runs_of(prefix)
    write_fragment("tab_training_cost.tex", sorted(set(sources)),
                   "$K$ & $R$ & $|\\mathcal{A}|$ & Params ($\\times 10^6$) & "
                   "Episodes & Wall clock (h) & Decisions/s", rows)


def main():
    print(f"result 目录: {RESULT}")
    print(f"输出目录:   {OUT}\n")
    tab_ratio()
    tab_capacity()
    tab_picktime()
    tab_layout()
    tab_ablation()
    tab_state_capacity()
    tab_training_cost()
    print("\n完成。论文中仍以表格出现的片段（tab_ratio / tab_capacity / "
          "tab_capacity_rules_sweep / tab_picktime / tab_ablation / "
          "tab_training_cost）与 manuscript.tex 对应表格的 tabular 主体应逐字"
          "一致；tab_layout / tab_state_capacity 的数字以行内形式出现在正文。")


if __name__ == "__main__":
    sys.exit(main())
